import OpenAI from "openai";

function getOpenAIClient(): OpenAI {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey === "sk-placeholder" || apiKey.startsWith("sk-proj-placeholder")) {
    throw new Error("OPENAI_API_KEY is not configured — set it in .env.local");
  }
  return new OpenAI({ apiKey });
}

export interface NarrativeContext {
  transaction: {
    txn_id: number;
    customer_id: string;
    customer_name: string;
    account_no: string;
    txn_date: string;
    txn_type: string;
    txn_amount: number;
    currency: string;
    channel: string | null;
    customer_type: string;
  };
  rule: {
    rule_name: string;
    description: string | null;
    risk_level: string;
    scenario_ref: string | null;
    target_case: string | null;
  };
}

export async function generateAlertNarrative(
  ctx: NarrativeContext
): Promise<string> {
  try {
    console.log(`[OpenAI] Generating narrative for alert on txn ${ctx.transaction.txn_id} (rule: ${ctx.rule.rule_name})`);
    console.log(`[OpenAI] Using API key: ${process.env.OPENAI_API_KEY?.slice(0, 12)}...${process.env.OPENAI_API_KEY?.slice(-4)}`);
    
    const openai = getOpenAIClient();
    
    const systemPrompt = `You are a financial crime analyst assistant for a Philippine bank. Given a flagged transaction and the rule that triggered it, write a concise 2-3 sentence explanation of why this transaction is suspicious. Use plain language suitable for a compliance officer. Reference specific amounts, patterns, and AMLC thresholds.`;

    const userPrompt = `Rule: "${ctx.rule.rule_name}" (${ctx.rule.risk_level})
${ctx.rule.scenario_ref ? `Scenario: ${ctx.rule.scenario_ref} — ${ctx.rule.description}` : ""}
${ctx.rule.target_case ? `Target case: ${ctx.rule.target_case}` : ""}

Transaction: ${ctx.transaction.customer_name} (${ctx.transaction.customer_type})
Account: ${ctx.transaction.account_no} | Date: ${ctx.transaction.txn_date}
Type: ${ctx.transaction.txn_type} | Amount: ${ctx.transaction.currency} ${ctx.transaction.txn_amount.toLocaleString()}
Channel: ${ctx.transaction.channel || "N/A"}

Explain why this is suspicious.`;

    const response = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      max_tokens: 250,
      temperature: 0.3,
    });

    const narrative = response.choices[0]?.message?.content;
    if (narrative) {
      console.log(`[OpenAI] ✅ Generated narrative (${narrative.length} chars)`);
      return narrative;
    }
    
    console.log(`[OpenAI] ⚠️ Empty response, using fallback`);
    return generateFallbackNarrative(ctx);
  } catch (err: unknown) {
    const error = err as Error;
    console.error(`[OpenAI] ❌ Error generating narrative:`, error.message || error);
    return generateFallbackNarrative(ctx);
  }
}

export function generateFallbackNarrative(ctx: NarrativeContext): string {
  return `Alert generated by rule "${ctx.rule.rule_name}" (${ctx.rule.risk_level} severity). Transaction of ${ctx.transaction.currency} ${ctx.transaction.txn_amount.toLocaleString()} on ${ctx.transaction.txn_date} for customer ${ctx.transaction.customer_name} (${ctx.transaction.customer_type}). ${ctx.rule.description || "Review required."}`;
}
