import OpenAI from "openai";

function getOpenAIClient(): OpenAI {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey === "sk-placeholder" || apiKey.startsWith("sk-proj-placeholder")) {
    throw new Error("OPENAI_API_KEY is not configured — set it in .env.local");
  }
  return new OpenAI({ apiKey });
}

export interface NarrativeContext {
  transaction: {
    txn_id: number;
    customer_id: string;
    customer_name: string;
    account_no: string;
    txn_date: string;
    txn_type: string;
    txn_amount: number;
    currency: string;
    channel: string | null;
    customer_type: string;
  };
  rule: {
    rule_name: string;
    description: string | null;
    risk_level: string;
    scenario_ref: string | null;
    target_case: string | null;
  };
}

export async function generateAlertNarrative(
  ctx: NarrativeContext
): Promise<string> {
  try {
    console.log(`[OpenAI] Generating narrative for alert on txn ${ctx.transaction.txn_id} (rule: ${ctx.rule.rule_name})`);
    console.log(`[OpenAI] Using API key: ${process.env.OPENAI_API_KEY?.slice(0, 12)}...${process.env.OPENAI_API_KEY?.slice(-4)}`);
    
    const openai = getOpenAIClient();
    
    const systemPrompt = `You are a senior financial crime investigator narrating suspicious activity findings for a Philippine bank's compliance team. Write your analysis as a short narrative story — as if you're briefing a room of investigators.

Your style:
- Begin by setting the scene: who is the customer, what happened, when
- Build tension by revealing the suspicious pattern or anomaly
- Conclude with what this pattern typically indicates and why it warrants investigation
- Use specific PHP amounts, dates, and thresholds from AMLC regulations
- Write 3-5 sentences in a flowing narrative style — not bullet points
- Tone: professional but engaging, like a detective recounting a case

Example style: "On July 10th, an account belonging to Elena Bautista — dormant for over seven months — suddenly received a PHP 750,000 cash deposit at the Makati branch. No prior activity explains this influx. The amount exceeds the AMLC's PHP 500,000 covered transaction threshold, and the dormancy pattern is consistent with mule account activation seen in cyber-heist laundering schemes."`;

    const userPrompt = `Rule triggered: "${ctx.rule.rule_name}" (${ctx.rule.risk_level} severity)
${ctx.rule.scenario_ref ? `Detection scenario: ${ctx.rule.scenario_ref} — ${ctx.rule.description}` : ""}
${ctx.rule.target_case ? `Typical case type: ${ctx.rule.target_case}` : ""}

The subject:
- Customer: ${ctx.transaction.customer_name} (${ctx.transaction.customer_type})
- Account: ${ctx.transaction.account_no}
- Transaction date: ${ctx.transaction.txn_date}
- Transaction type: ${ctx.transaction.txn_type}
- Amount: ${ctx.transaction.currency} ${ctx.transaction.txn_amount.toLocaleString()}
- Channel: ${ctx.transaction.channel || "N/A"}

Narrate this suspicious finding as a story for the investigation team.`;

    const response = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      max_tokens: 400,
      temperature: 0.5,
    });

    const narrative = response.choices[0]?.message?.content;
    if (narrative) {
      console.log(`[OpenAI] ✅ Generated narrative (${narrative.length} chars)`);
      return narrative;
    }
    
    console.log(`[OpenAI] ⚠️ Empty response, using fallback`);
    return generateFallbackNarrative(ctx);
  } catch (err: unknown) {
    const error = err as Error;
    console.error(`[OpenAI] ❌ Error generating narrative:`, error.message || error);
    return generateFallbackNarrative(ctx);
  }
}

export function generateFallbackNarrative(ctx: NarrativeContext): string {
  return `Alert generated by rule "${ctx.rule.rule_name}" (${ctx.rule.risk_level} severity). Transaction of ${ctx.transaction.currency} ${ctx.transaction.txn_amount.toLocaleString()} on ${ctx.transaction.txn_date} for customer ${ctx.transaction.customer_name} (${ctx.transaction.customer_type}). ${ctx.rule.description || "Review required."}`;
}
